[pytest]

markers =
    smoke: быстрый набор
    regress: полный набор (включает smoke)

testpaths = tests

console_output_style = progress

filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
